### ISSUE TITLE
Debian 12 cannot be deployed because /mnt/etc/cloud/cloud.cfg does not exist

### ISSUE THREAD

**Issue by UntouchedWagons** [canonical/packer-maas#206]
I'm trying to deploy debian 12 to a proxmox VM but deployment fails because `/mnt/etc/cloud/cloud.cfg` does not exist.

[moving-walrus.internal.untouchedwagons.com-installation-output-2024-02-09.log](https://github.com/canonical/packer-maas/files/14223766/moving-walrus.internal.untouchedwagons.com-installation-output-2024-02-09.log)

**Comment by gsperry2011** [comment]
I am also running into this and have done a bit of testing around this. I am not 100% sure WHY it occurs but I understand how to work around it. I believe it is because the second `sed` command is being ran before the first one completes and thus it is unable to find the file. That being said, I also tested putting a `sleep 10` between the two `sed` steps and that did not resolve the issue so i'm not exactly positive there.

What DOES fix it is calling the `sed` commands and forcing them to run seqentually via `&&`. Example: 
```
late_5: sed -i 's@ubuntu.com/ubuntu@debian.org/debian@g;s@archive@deb@g;s@ubuntu@debian@g;s@Ubuntu@Debian@g;' /mnt/etc/cloud/cloud.cfg && sed -i 's/security.debian.org\/debian/security.debian.org/g' /mnt/etc\/cloud/cloud.cfg
```

I plan to make a PR for this change

**Comment by UntouchedWagons** [comment]
Okay, I copied the new preseed file and was able to deploy a debian VM but it appears that the cloudinit I provided was ignored, or possibly I didn't provide enough info or the right directives:

```
#cloud-config
# https://cloudinit.readthedocs.io/en/latest/reference/examples.html
packages:
 - qemu-guest-agent
 - openssh-server

users:
  - default
  - name: UntouchedWagons
    gecos: UntouchedWagons
    primary_group: UntouchedWagons
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_import_id:
      - gh:UntouchedWagons
runcmd:
  - [ systemctl, enable, --now, qemu-guest-agent ]
  - [ systemctl, enable, --now, ssh ]
```
